source :rubygems

gem 'mechanize'
gem 'mongo'
gem 'bson_ext'
gem 'grape'
gem 'builder'
gem 'ruby-progressbar', :require => 'progressbar'
gem 'foreman'
gem 'thin'
gem 'tire'
gem 'yajl-ruby', :require => 'yajl/json_gem'
gem 'psych'
gem 'redis'

group :development do
  gem 'pry'
end
