task :copy_assets do
  system "rm -rf public/*"
  system "mkdir public/js"
  system "mkdir public/templates"
  system "cp -f *.html public/"
  system "cp -f js/*.js public/js/"
  system "cp -rf templates public/"
  system "compass compile --quiet"
  system "coffee -o public/js --compile js/*.coffee &> /dev/null"
end

task :default do
  system "./watch.sh"
end
